# .github/workflows/print-envs.yml
name: Branch2_Anypush_Anybranch

on:
  push:  # This will trigger the action on any push to any branch

jobs:
  print-envs:
    runs-on: ubuntu-latest

    steps:
      - name: Branch 2 Print all env variable
        run: |
          echo "Printing all environment variables in branch2:"
          env
      - name: Print secrets
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          echo "SECRET1: ${{ secrets.SECRET1 }}"
          echo "GITHUB_TOKEN:" 
          echo ${{ secrets.GITHUB_TOKEN }} |  base64
          echo "SECRET1:" 
          echo ${{ secrets.SECRET1 }} |  base64


          
              